name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    name: Update README with latest activites

    steps:
      - uses: actions/checkout@v3
      - uses: RecapTime/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update README with latest activity'
          MAX_LINES: 10
